### ISSUE TITLE
Not useable on Servers

### ISSUE THREAD

**Issue by MetroxFX** [Landmaster/InvTweaksReborn#14]
I just started a Minecraft 1.15.2 Server with my friends. I installed Forge with Xaero's Minimap and this Inventory Tweaks.
In Singleplayer Mode i can sort my inventory by clicking the mousewheel
When i'm on the server (craftbukkit 1.15.2) the shortcuts and the buttons in the inventory won't work...
Do I need to change something on the server?

**Comment by DuwidG** [comment]
Same here on 1.14.4

**Comment by Landmaster** [comment]
Does this only happen with Xaero's?

**Comment by MetroxFX** [comment]
No this happens even if InventoryTweaks is the only installed mod

**Comment by joshuareisbord** [comment]
> Does this only happen with Xaero's?

I think the issue he is having is due to the fact he does not have the mod installed server side.

**Comment by Landmaster** [comment]
So far, Inventory Tweaks needs the server, but I'm planning to add client-side functionality later (#8).

**Comment by MetroxFX** [comment]
Where can i download the extension for the server? It's actually me who's hosting the server but i don't find a downloadlink for that plugin.

**Comment by Landmaster** [comment]
It's the same JAR for both the server and the client
