### ISSUE TITLE
Full inventory sort.

### ISSUE THREAD

**Issue by LordHarkon** [Landmaster/InvTweaksReborn#18]
I don't know if it's a bug, or maybe just an intended feature, but if a chest is full, with no open slots, it cannot be sorted, through all of the available methods, I have to open a slot and then sort it.

**Comment by Landmaster** [comment]
Does this happen in SP, or only in client-side-only MP?

**Comment by LordHarkon** [comment]
I have not tested it on single player. I am playing on a server made by me, with a friend. And I have only tested it there. The mod is included into both the client and the server.

**Comment by LordHarkon** [comment]
![image](https://user-images.githubusercontent.com/12067203/78679536-06853280-78f3-11ea-8b4b-ad654184efff.png)
^^ This, does not let me sort it. I am SP right now, but it's the same on MP. The items inside don't matter.
![image](https://user-images.githubusercontent.com/12067203/78679606-1ef54d00-78f3-11ea-8690-c130c499b553.png)
^^ This, lets me sort the items, as seen in the next image.
![image](https://user-images.githubusercontent.com/12067203/78679671-33394a00-78f3-11ea-8ee4-409c0529d3fb.png)
