### ISSUE TITLE
Suggestion: BetterCrates support

### ISSUE THREAD

**Issue by zadzial** [Landmaster/InvTweaksReborn#4]
Doing well with vanilla inventory, very appreciative. Is it possible to extend the functionality to BetterCrates and other, similar mods (Dank Storage, etc)? I realise this is still in the early stages so it's not any form of negative critique. Thanks for your work, I've been missing Tweaks and my pathetic coding skills prevent me doing it myself.

**Comment by Landmaster** [comment]
IT Reborn already supports most modded containers right out of the box. I even tested Better Crates specifically, and it works with it.

**Comment by zadzial** [comment]
I was hoping you’d  get the idea that it wasn’t working for Better Crates if it was supposed to support it. I know it might be a conflict with other mods (no other sorter, though). In fact, the only response I had with Tweaks with Better Crates so far is the deletion of everything inside the crate – the loss of a hell of a lot of work. 

 

A bit fast closing the thread there, but hey, it’s your mod.

**Comment by Landmaster** [comment]
You should have made that clear when you were opening the issue…

**Comment by zadzial** [comment]
It worked! And the inventory still exists!  

Thankyou!
