### ISSUE TITLE
1.15 Support ETA

### ISSUE THREAD

**Issue by tpelado** [Landmaster/InvTweaksReborn#5]
Hey,

First of all, thanks for taking up on Inventory Tweaks.

I reckon we won't see anything until the MCP is updated to 1.15, but I'm asking anyway, do you have any idea when the 1.15 version will be up ? 

Thanks for your work,

**Comment by Landmaster** [comment]
It'll probably be not long after Forge is released for that version, since IIRC, there's not that many changes from 1.14 -> 1.15.
