### ISSUE TITLE
Having multiple copies of items causes mass deletion.

### ISSUE THREAD

**Issue by Azanorashit** [Landmaster/InvTweaksReborn#7]
On a server I had this mod added to, one of the users complained that chopping a tree down, with the tree chopper mod active, deleted every single stone axe in his inventory after the first one broke, and now while I was spawning chickens with normal eggs, after the first stack was used, the other 16 stacks I had in my inventory disappeared, and relogging did not fix it.

**Comment by Landmaster** [comment]
Try reproducing with the minimal amount of mods possible.
