### ISSUE TITLE
[1.15.2] Possible dupe-bug

### ISSUE THREAD

**Issue by Quu1337** [Landmaster/InvTweaksReborn#9]
I am not 100% sure this issue is caused by invtweaksreborn, but disabling it makes the problem go away.

1) Vanilla crafting grid
2) insert recipe
3) middle-mouse-click the output item
4) sorts recipe + output into the grid
5) get recipe parts and output item out of it, making it freeeeeee.

Forge: 31.1.0
InvTweaksReborn: 1.15.2-1.0.0

All The Mods 5, 1.4

**Comment by TheBeardedQuack** [comment]
I've successfully replicated the issue on my setup. I did notice that this doesn't appear to be happening with the crafting built into the inventory, it may be worth seeing if it's also there with other mod crafting slots.

I'm using just the raw git repo with no changes and no additional mods installed. Also rebinding the "sort inventory under mouse" key causes the issue to now happen on that key press.

**Comment by Gbergz** [comment]
Very easily replicated this issue. Needs to be fixed asap!

**Comment by Gbergz** [comment]
Awesome that it got fixed for 1.15.2! But what about 1.14.4? The dupe-issue is still present there.

**Comment by Landmaster** [comment]
The fix will also come for 1.14, though right now I'm focusing on bug fixing in 1.15 first since it seems that modpack authors are mostly skipping 1.14.

**Comment by Gbergz** [comment]
Gotcha! Was about to post an update to my modpack [Limitless](https://www.curseforge.com/minecraft/modpacks/tnp-limitless), i'll post it anyways hoping players won't abuse it. Glad the fix is coming though! 👍
